<script lang="ts" setup>
import { PublicKey } from "@solana/web3.js";
import { useWallet } from "solana-wallets-vue"

const $router = useRouter()
const $auth = useAuth()
const { wallet } = useWallet()
const { connection } = useConnection()
const { program, BLOG_ADDRESS } = useContract()
const $loading = useLoading()

const checkIsConnected = () => {
  if (!$auth.isConnected.value || !$auth.check()) {
    $router.push("/")
  }
}
checkIsConnected()
watch($auth.isConnected, (val) => {
  checkIsConnected()
})

const predictedUserAddress = computed(() => {
  return getPdaUserAccount($auth.wallet.value ? ($auth?.wallet?.value).toBuffer() : Buffer.from(""))
})

const userModel = reactive({
  name: $auth.isLogged.value ? ($auth.user.value?.data?.name || '') : '',
  email: $auth.isLogged.value ? ($auth.user.value?.data?.email || '') : '',
  image: $auth.isLogged.value ? ($auth.user.value?.data?.image || '') : 'https://api.dicebear.com/5.x/pixel-art/svg?seed=Example&autogenerated',
})

watch(userModel, (val) => {
  if (`${val.image}`.includes('autogenerated')) {
    userModel.image = 'https://api.dicebear.com/5.x/pixel-art/svg?seed=' + (val.name === '' ? 'Example' : val.name) + '&autogenerated'
  }
})

const createProfile = async () => {
  try {
    if (userModel.name.replaceAll(' ', '') === '') return alert('Name is required')
    if (userModel.email.replaceAll(' ', '') === '') return alert('Email is required')
    if (userModel.image.replaceAll(' ', '') === '') return alert('Image is required')

    $loading.show()
    const tx = await program.value.methods
      .createUser(
        userModel.name,
        userModel.email,
        userModel.image,
      )
      .accounts({
        userAccount: predictedUserAddress.value,
        blogAccount: BLOG_ADDRESS,
      })
      .rpc()

    //
    await $auth.check()
    window.location.reload()
  } catch (error) {
    console.log(error)
  }
  $loading.hide()
}
</script>

<template>
  <div class="">
    <Card>
      <template #header>
        <template v-if="!$auth.user.value">
          <div class="font-bold text-xl">Create Your Profile</div>
          <div class="text-sm font-thin">You must create your profile to continue</div>
        </template>
        <template v-else>
          <div class="font-bold text-xl">Your Profile</div>
        </template>
      </template>
      <div class="flex flex-col space-y-4">
        <div class="flex">
            <div class="w-1/5 mt-2">Your Wallet Address</div>
            <div class="flex-1">
              <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" placeholder="Your Wallet Address" readonly :value="$auth.wallet.value" />
            </div>
        </div>
        <div class="flex">
          <div class="w-1/5 mt-2">User Address</div>
          <div class="flex-1">
            <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" placeholder="Your Wallet Address" readonly :value="predictedUserAddress" />
            <div class="font-thin text-sm mt-1">
              * this is your user address (pda), generate automatically from seed (program seed + your wallet address)
            </div>
          </div>
        </div>
        <div class="flex">
          <div class="w-1/5 mt-2">Name</div>
          <div class="flex-1">
            <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" placeholder="Your Name" v-model="userModel.name" />
          </div>
        </div>
        <div class="flex">
          <div class="w-1/5 mt-2">Email</div>
          <div class="flex-1">
            <input type="email" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" placeholder="Your Email" v-model="userModel.email" />
          </div>
        </div>
        <div class="flex">
          <div class="w-1/5 mt-2">Avatar</div>
          <div class="flex-1 flex space-x-4">
            <div class="w-16 h-16 bg-slate-700 rounded-full overflow-hidden flex">
              <img :src="userModel.image" class="w-16 h-16 inline-block" />
            </div>
            <div class="flex-1 flex items-center">
              <input type="text" class="w-full border-2 border-white/10 rounded-lg px-4 py-2 bg-transparent text-white read-only:bg-slate-800" placeholder="Your Avatar URL" v-model="userModel.image" />
            </div>
          </div>
        </div>
        <div class="flex items-center justify-end">
          <button v-if="$auth.isConnected.value && !$auth.isLogged.value" class="bg-primary-500 rounded-lg px-4 py-2 text-white font-bold" @click="createProfile">
            Create Profile
          </button>
          <button v-else class="bg-primary-500 rounded-lg px-4 py-2 text-white font-bold disabled:opacity-50" disabled>
            Update Profile (coming soon)
          </button>
        </div>
      </div>
    </Card>
  </div>
</template>
