[features]
seeds = false
skip-lint = false
[programs.devnet]
contract = "D8kSsEmQm9ob4erUySzusYJWFh79snxQN3CcmuNaiS16"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/viandwi24/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
